### PR TITLE
[window-buttons] Automatically use icons from current theme

### PR DESCRIPTION
**Pull request by gabrielfin**
From issue #1 

I created a class that looks in the following paths:
- `~/.icons/mate-window-applets/<theme>`
- `~/.themes/<theme>/metacity-1`
- `~/.themes/<theme>/unity`
- `/usr/share/themes/<theme>/metacity-1`
- `/usr/share/themes/<theme>/unity`

for icons matching the pattern: `<prefix>_<type>_<state>_<action>.<extension>`
where 
- `<prefix>`: empty, "button" or "icon"
- `<type>`: "close", "minimize", "maximize" , "unmaximize"/"restore"
- `<state>`: "focused"/empty, "unfocused"
- `<action>`:  "normal"/empty, "prelight", "pressed"
- `<extension>`: "png", "svg"

It matches by most to less common, according to what I've seen in many themes. For example, it matches first with `close_focused_normal.png` (most themes), then `close_focused.png`, then `close_normal.png` (WinMe theme), then `close.png`, then `icon_close.png`, etc. And returns the first file that matches.
That's why the code has multiple `for` loops, because it matches multiple combinations.

Some options are rare, like the "button" or "icon" prefixes. But since they are searched last, they shouldn't make any difference. I made the code in a way that we could easily add or remove combinations and alternate names.

If it doesn't find an icon for either "close", "maximize" or "minimize" buttons, then it falls back to icons located in `/usr/share/pixmaps/mate-window-applets`. I put the icons from the "Black" theme, but perhaps we could ship a better one.

Also, now the theme is automatically detected from the Marco settings.
And also added the "button pressed" effect, which wasn't included before.

### CODE REVIEW

**Comment by vkareh** [comment]
I would also add `/usr/local/share`, after $HOME, but before `/usr/share`.

By the way, this code looks very good! I will look in more detail and test it out this week.

**Comment by flexiondotorg** [comment]
Great work @gabrielfin. Please add `/usr/local/share` as @vkareh requests 👍

**Comment by vkareh** [comment]
@gabrielfin, this works really well, great stuff!

One "issue" I noticed is that High Contrast, High Contrast Inverse, TraditionalGreen, and TraditionalOk all use the same icons, which are just black... Not a blocker for me, however, on High Contrast Inverse, because the fallback are black, means that the users won't see the icons at all (unless they hover on them). Considering that High Contrast themes are typically used by visually impaired users, that _might_ be a blocker. Any chance a white version of the icons can be forced for this particular theme?

Other than that, this looks really good on my system. Tested with all themes available in upstream MATE and Ubuntu MATE (not third-party ones).

**Comment by gabrielfin** [comment]
@vkareh 
I added back the "Black" and "White" fallback themes. One of those themes is selected as fallback according to the luminance of the applet's text foreground color. So, for HighContrast, TraditionalGreen, and TraditionalOk it will chose "Black", and for HighContrastInverse it will choose "White". Of course, this means it should work with any theme.

I'm not sure about the OOP "correctness" of the code, so if you want me to change anything, just let me know.

Also added `/usr/local/share` paths.

**Comment by vkareh** [comment]
> not sure about the OOP "correctness" of the code

I don't know a whole lot about vala, so I can't really comment intelligently about it :D

But there's something weird about assigning `this.applet_style_context` and then using `applet_style_context` straight up in another function. But again, this may be how vala works, so *shrug*

**Comment by vkareh** [comment]
(Also, I'm looking at this code on my phone, so it's hard to see the entire code, and also it means I can't really test this until I'm at my computer, sorry!!)

**Comment by gabrielfin** [comment]
> But there's something weird about assigning this.applet_style_context and then using applet_style_context straight up in another function. But again, this may be how vala works, so shrug

:D I agree... and also, my first time with Vala. I don't know what the coding conventions in Vala are. In the rest of the code, `this` is sometimes used and sometimes isn't.

> (Also, I'm looking at this code on my phone, so it's hard to see the entire code, and also it means I can't really test this until I'm at my computer, sorry!!)

Don't worry, there's no rush.

**Pull request merged**
